# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: Tolga Karataş
# Website URL
baseURL: 'https://tolgakaratas.com/'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

menus:
  main:
    - name: "Bio"
      url: "/"
      weight: 10
    - name: "Papers"
      url: "/#papers"
      weight: 11
    - name: "Talks"
      url: "/#talks"
      weight: 12
    - name: "News"
      url: "/#news"
      weight: 13
    - name: "Experience"
      url: "experience/"
      weight: 20
    - name: "Projects"
      url: "projects/"
      weight: 30
    - name: "Teaching"
      url: "teaching/"
      weight: 40

languages:
  tr:
    menus:
      main:
        - name: "Hakkımda"
          url: "/"
          weight: 10
        - name: "Yayınlar"
          url: "/#papers"
          weight: 11
        - name: "Konuşmalar"
          url: "/#talks"
          weight: 12
        - name: "Haberler"
          url: "/#news"
          weight: 13
        - name: "Deneyim"
          url: "experience/"
          weight: 20
        - name: "Projeler"
          url: "proje/"
          weight: 30
        - name: "Eğitim"
          url: "teaching/"
          weight: 40
  ru:
    menus:
      main:
        - name: "Обо мне"
          url: "/"
          weight: 10
        - name: "Публикации"
          url: "/#papers"
          weight: 11
        - name: "Выступления"
          url: "/#talks"
          weight: 12
        - name: "Новости"
          url: "/#news"
          weight: 13
        - name: "Опыт"
          url: "opyt/"
          weight: 20
        - name: "Проекты"
          url: "proekt/"
          weight: 30
        - name: "Обучение"
          url: "obuchenie/"
          weight: 40

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep