en:
  languageCode: en-us
  title: Tolga Karataş
  contentDir: content/en

tr:
  languageCode: tr
  title: Tolga Karataş
  contentDir: content/tr
  params:
    description: Tolga Karataş'ın kişisel web sitesi

ru:
  languageCode: ru
  title: Толга Караташ
  contentDir: content/ru
  params:
    description: Персональный сайт Толга Караташа